# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Flask

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: cp -a /home/administrator/github-actions/_work/jonathanohlson.se/jonathanohlson.se/server/. /var/server/api-service/